image: node
environment:
  YARN_CACHE_FOLDER: C:\yarn-cache
  YARN_VERSION: 1.22.22

install:
  - yarn install

build_script:
  - yarn build

artifacts:
  - path: dist
    name: dist

deploy:
  provider: GitHubPages
  artifact: dist
  auth_token:
    secure: YOUR_GITHUB_TOKEN
  on:
    branch: main
