version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: "18.17.1"
  YARN_VERSION: "1.22.22"
  
install:
  # Установка Node.js (новый способ)
  - ps: |
      $nodeUrl = "https://nodejs.org/dist/v$env:nodejs_version/node-v$env:nodejs_version-win-x64.zip"
      Invoke-WebRequest -Uri $nodeUrl -OutFile "node.zip"
      Expand-Archive -Path "node.zip" -DestinationPath "$env:ProgramFiles\nodejs" -Force
      $env:Path = "$env:ProgramFiles\nodejs;" + $env:Path
  # Проверки
  - node --version
  - yarn --version
  - yarn install

build_script:
  - yarn build

artifacts:
  - path: dist
    name: dist

on_success:
  - yarn deploy

# Для GitHub Pages (альтернативный вариант)
deploy:
  provider: GitHub
  artifact: dist
  auth_token:
    secure: YOUR_ENCRYPTED_GITHUB_TOKEN  # Замените на реальный токен
  on:
    branch: main